#!/usr/bin/env php
<?php declare(strict_types=1);

require_once('vendor/autoload.php');

use DI\Container;
use willitscale\Streetlamp\Streetlamp;

try {
    array_shift($argv);
    new Container()
        ->make(Streetlamp::class)
        ->command($argv);
} catch (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
    exit(1);
}
